site_name:        IRENA FlexTool
repo_url:         https://github.com/irena-flextool/flextool
site_description: IRENA FlexTool is an energy and power systems model for understanding the role of variable power generation in future energy systems. It performs capacity expansion planning as well as operational planning.
site_author: Juha Kiviluoma, VTT Technical Centre of Finland
copyright: IRENA

theme: readthedocs

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code

docs_dir: 'docs'

nav:
  - Introduction: 
    - 'Introduction': index.md
  - Getting started: 
    - 'Overview of the interfaces to Flextool': interface_overview.md
    - 'Installing IRENA FlexTool - SpineToolbox': install_toolbox.md
    - 'Installing IRENA FlexTool - Web interface': install_web_interface.md
  - Documentation:
    - 'Tutorial': tutorial.md
    - 'Model parameters': reference.md
    - 'Model outputs': results.md
    - 'How to': how_to.md
  - Interfaces:
    - 'Toolbox interface': spine_toolbox.md
    - 'Browser interface': browser_interface.md
 