[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "flextool"
version = "3.8.0"
description = "IRENA FlexTool is an energy and power systems model for understanding the role of variable power generation in future energy systems."
requires-python = ">=3.8,<3.13"
dependencies = [
    "pandas",
	"spinedb-api",
]