"""``2_day_stochastic_dispatch`` (no-storage variant) — A6 parity test.

Variant: ``hydro_reservoir.node_type = commodity`` overrides the storage
binding so the fixture exercises the **pdt_branch_weight** factor in
isolation.  ``non_anticipativity_storage_use`` is moot here (no
``nodeState``); the only delta vs deterministic is the per-(d, t)
operational probability multiplier on every dispatch-class objective term.

Pre-A6: polar_high was 4.00× higher than flextool — clean smoking-gun for
the missing 0.25-per-branch weight factor on a 4-branch fixture.
Post-A6: machine-epsilon parity.

Fixture is generated by :mod:`tests._gen_2day_stochastic_dispatch`.
"""

import polars as pl

from polar_high import Problem
from flextool.engine_polars import build_flextool, load_flextool
import pytest

pytestmark = pytest.mark.solver


# Phase 3d: scenario added to ``stochastics.json`` via
# ``tests/fixtures/_augment_phase3d.py``.  ``2_day_stochastic_dispatch``
# + alternative ``no_storage_override`` (drains hydro_reservoir state by
# setting ``node_type='commodity'``).
SCENARIO = "2_day_stochastic_dispatch_no_storage"


def test_2day_stochastic_dispatch_no_storage_parity(scenario_workdir):
    work = scenario_workdir(SCENARIO, db_fixture="stochastic")
    data = load_flextool(work)

    # Fixture sanity — stochastic data populated.
    assert data.pdt_branch_weight is not None, (
        "pdt_branch_weight should be populated for a stochastic fixture")
    assert data.pd_branch_weight is not None
    assert data.dt_non_anticipativity is not None
    assert data.period_branch_full is not None
    # 4 branches with weight 0.25 each — siblings sum to 1.0 per (d, t).
    weights = data.pdt_branch_weight.frame
    sample = (weights
        .filter((pl.col("d") == "period1") & (pl.col("t") == "t0001")))
    assert sample.height == 1
    # Single (d=period1, t=t0001) row — siblings sit on (d=period1_upper, t),
    # etc.  Sum across siblings sharing the same time index must be 1.0.
    siblings_t1 = (weights
        .filter(pl.col("t") == "t0001")
        .filter(pl.col("d").is_in([
            "period1", "period1_upper", "period1_lower", "period1_mid"])))
    assert abs(float(siblings_t1["value"].sum()) - 1.0) < 1e-12

    pb = Problem()
    build_flextool(pb, data)
    sol = pb.solve()
    assert sol.optimal

    flextool_obj = pl.read_parquet(
        work / "output_raw" / "v_obj__2day_dispatch.parquet"
    )["objective"][0]
    rel = abs(sol.obj - flextool_obj) / max(1.0, abs(flextool_obj))
    assert rel < 1e-6, (
        f"obj mismatch: polar_high={sol.obj}, flextool={flextool_obj}, rel={rel}"
    )
