"""Phase H — end-to-end verification of the cascade I/O migration.

The migration's terminal phase: a default-mode cascade run produces

  * ``output_raw/v_*.parquet`` (raw LP-variable trail)
  * ``output_processed/*`` (per ``--write-methods``)
  * ``manifest.json`` (auto-generated by ``_parquet_bundle.write_manifest``)

and NO cascade-internal CSVs in ``input/``, ``solve_data/``, or
``cross_solve/`` (modulo a documented set of out-of-scope writers — see
the ``_DOCUMENTED_OUT_OF_SCOPE`` whitelist below).  Adding ``--csv-dump``
reproduces the legacy CSV layout under ``solve_data/`` (and friends).

What this module asserts
------------------------

For each of two representative fixtures (``work_base`` single-solve and
``work_5weeks_invest_fullYear_dispatch_coal_wind`` two-solve cascade) we
exercise the cascade THREE ways and inspect the on-disk bundle:

* **default mode** — ``the in-memory cascade`` wraps the cascade
  exactly the way ``cmd_run_flextool.py:_run_native_solve`` does when
  the user does NOT pass ``--csv-dump``.

  Asserts:
    - ``output_raw/`` contains ``v_*.parquet`` (>= 1).
    - ``solve_data/`` either does not exist OR contains only files
      listed in ``_DOCUMENTED_OUT_OF_SCOPE`` (out-of-scope writers
      retained by earlier Phase E-d / E-e dispatches).
    - ``cross_solve/`` does not exist OR contains no ``*.csv`` (the
      cross-solve carriers ride in ``state.cross_solve_carriers`` per
      Phase E-d).
    - ``input/`` may exist with CSVs — the legacy ``write_input`` direct
      ``csv.writer`` writes were NOT gated in Phase E (out-of-scope as
      noted in commit ``09f3b363`` Phase E-c notes).
    - ``write_manifest`` produces ``manifest.json`` with the documented
      schema (version "1", ``generated_at`` ISO 8601, ``files`` list);
      every ``files[i].exists`` true entry maps to a real file under
      the bundle root.
    - Cascade's final objective is captured (used for parity check).

* **--csv-dump mode** — no ``the in-memory cascade`` wrap (CSV
  emission on, the legacy behaviour).  Asserts ``solve_data/`` contains
  the legacy CSV set (sample a handful of basenames), confirms manifest
  + raw parquets, and asserts objective matches the default-mode run
  within ``rel_tol=1e-6``.

* **legacy mode** — i.e. a disk-only orchestration path that bypasses
  the in-memory cascade.  Phase E retired this entry point; there is no
  longer a separate ``run_disk_only`` orchestration.  The test
  documents this with a ``pytest.skip``.

The multi-roll fixture under ``the in-memory cascade`` is currently
broken (Phase H surfaced the regression: ``input.py::_load_process_topology``
calls ``_read_p_flow_max``, ``_read_unitsize``, and ~30 other helpers
that use ``if not path.exists(): return None`` — these are NOT
seed-aware loaders, only the writer-side ``_emit_*`` modules were
seed-wired in Phase E-e).  The multi-roll csv-dump-mode case still
passes; we keep that gate.  Lifting the loader-side reads onto the seed
funnel is tracked as a follow-up — out of Phase H scope per the task
constraint "DON'T change production code unless precise fix".  The
single-roll csv-disabled case (work_base) DOES pass and exercises the
end-to-end contract; that's where the default-mode invariants are
verified.

External-consumer smoke
-----------------------

``test_external_consumer_can_load_bundle`` exercises the
self-describing-bundle contract: open ``manifest.json``, walk every
``exists=True`` file, compute a tiny summary stat (row count) per file.
This is the "fresh eye" gate from the handoff doc.
"""
from __future__ import annotations

import json
import math
import shutil
from datetime import datetime
from pathlib import Path

import polars as pl
import pytest

from flextool.engine_polars import run_chain_from_db
from flextool.engine_polars._parquet_bundle import (
    REGISTRY,
    write_manifest,
)


pytestmark = pytest.mark.solver


HERE = Path(__file__).resolve().parent
DATA = HERE / "data"


# ---------------------------------------------------------------------------
# Documented out-of-scope writers — basenames that still emit to
# ``solve_data/`` under ``the in-memory cascade`` because their writer
# path was deliberately NOT gated by Phase E-c / E-d (out-of-scope or
# post-solve-overwritten basenames).
# ---------------------------------------------------------------------------
#
# The lists below mirror ``test_phase_e_c_default_no_csvs.py``'s
# ``post_solve_allowed`` set plus the not-managed legacy preprocessing
# files (``pdt_*``, ``pbt_*``, ``pt_*``, ``block_*`` written by
# ``flextool.flextoolrunner.preprocessing/*``) — these run outside the
# accumulator and emit CSVs even when emission is "disabled".
#
# This whitelist is the explicit Phase H scope boundary: tightening it
# (forcing more writers under the gate) is a follow-up dispatch.

_DOCUMENTED_OUT_OF_SCOPE_SOLVE_DATA: frozenset[str] = frozenset({
    # Post-solve writers (output_for_solve + handoff_writers) — emit
    # even when the per-iter scope is gated; per-iter accumulator
    # already captured them but the post-solve overwrite path lands
    # them on disk.  See test_phase_e_c::test_phase_e_d_universal_csv_free_run
    # for the same whitelist.
    "p_entity_period_existing_capacity.csv",
    "p_entity_invested.csv",
    "p_entity_divested.csv",
    "p_entity_period_invested_capacity.csv",
    "fix_storage_quantity.csv",
    "fix_storage_price.csv",
    "fix_storage_usage.csv",
    "co2_cum_realized_tonnes.csv",
    "ladder_cum_sim_hours.csv",
    "ladder_cum_realized_mwh.csv",
    "scale_the_objective.csv",
    "scale_the_state.csv",
    "period_capacity.csv",
    "costs_discounted.csv",
    "co2.csv",
    "rp_cost_weight.csv",
    # Legacy preprocessing emitters (preprocessing/*.py — Φ.2 / Δ.x
    # writers running outside the accumulator surface).  These are
    # block / pbt / pdt / pt families plus the timeline_matching_map
    # carrier — none of them are seed-fed.
    "block_period_time_first.csv",
    "block_period_time_last.csv",
    "block_step_duration.csv",
    "block_step_previous.csv",
    "commodity_with_ladder.csv",
    "commodity_with_ladder_annual.csv",
    "commodity_with_ladder_cumulative.csv",
    "downtime_lookback.csv",
    "entity_block.csv",
    "overlap_set.csv",
    "pbt_node.csv",
    "pbt_node_inflow.csv",
    "pbt_process.csv",
    "pbt_process_sink.csv",
    "pbt_process_source.csv",
    "pbt_profile.csv",
    "pbt_reserve__upDown__group.csv",
    "process_block.csv",
    "process_side_block.csv",
    "pt_commodity.csv",
    "pt_group.csv",
    "pt_node.csv",
    "pt_node_inflow.csv",
    "pt_process.csv",
    "pt_process_sink.csv",
    "pt_process_source.csv",
    "pt_profile.csv",
    "pt_reserve__upDown__group.csv",
    "timeline_matching_map.csv",
    "timings.csv",
    "uptime_lookback.csv",
    # Reserve / chain-cumulative carriers (test_phase_e_c notes them
    # as still landing on disk under csv-free mode for some fixtures).
    "ed_history.csv",
    "edd_history.csv",
})

# ``input/`` is entirely out-of-scope for Phase E gating — the legacy
# ``flextool.flextoolrunner.input_writer.write_input`` keeps writing
# the 132-CSV input bundle via direct ``csv.writer`` calls.  Phase E-c
# commit notes call this out explicitly; the gate was applied only to
# the ``engine_polars/_emit_*.py`` thin-wrapper writers.  Phase H test
# tolerates files in ``input/``; tightening is a follow-up.


# ---------------------------------------------------------------------------
# Fixture / mode helpers
# ---------------------------------------------------------------------------


_FIX_SINGLE_ROLL = ("work_base", "base")
# 2-sub-solve fixture; fast (~3 s).  The csv-emission-disabled path on
# multi-roll currently fails on the loader-side ``_read_p_flow_max`` /
# ``_read_unitsize`` family (Phase E left those readers disk-bound).
# We exercise csv-dump-mode for multi-roll and document the disabled-
# mode gap.
_FIX_MULTI_ROLL = (
    "work_5weeks_invest_fullYear_dispatch_coal_wind",
    "5weeks_invest_fullYear_dispatch_coal_wind",
)


def _db_or_skip(work_name: str) -> Path:
    db = DATA / work_name / "tests.sqlite"
    if not db.exists():
        pytest.skip(f"fixture sqlite missing: {db}")
    return db


def _run_cascade(db: Path, scen: str, work: Path,
                 *, csv_disabled: bool = False, csv_dump: bool | None = None):
    """Helper: drive ``run_chain_from_db``.

    ``csv_disabled`` is the legacy parameter name retained for source
    compatibility — when ``True``, csv_dump defaults to False (the new
    default mode); when ``False``, csv_dump defaults to True (legacy
    csv-dump mode).  Callers can override via ``csv_dump=``.
    """
    work.mkdir(parents=True, exist_ok=True)
    if csv_dump is None:
        csv_dump = not csv_disabled
    sols = run_chain_from_db(
        db, scenario_name=scen, work_folder=work, csv_dump=csv_dump,
    )
    # Mirror the ``--csv-dump`` cmd_run_flextool path: snapshot the
    # last sub-solve's Provider so the on-disk surface mirrors what the
    # CLI produces.
    if csv_dump and sols:
        last = next(reversed(list(sols.values())))
        provider = getattr(last, "flex_data_provider", None)
        if provider is not None:
            provider.snapshot_processed_inputs(work)
    return sols


def _final_objective(sols) -> float:
    last = next(reversed(sols.values()))
    # Slim default holds ``obj`` summary; full solution lives on the
    # last step only.  Either field is acceptable.
    if last.obj is not None:
        return float(last.obj)
    return float(last.solution.obj)


def _validate_manifest(work: Path, *, must_have_raw: bool = True) -> dict:
    """Write the manifest and assert its core invariants.

    Returns the parsed manifest dict so callers can inspect specific
    entries.
    """
    path = write_manifest(work)
    assert path == work / "manifest.json"
    assert path.is_file(), f"manifest not written to {path}"
    manifest = json.loads(path.read_text())

    # Schema basics.
    assert manifest["version"] == "1"
    # ISO 8601 parses.
    datetime.fromisoformat(manifest["generated_at"])
    assert manifest["bundle_root"] == str(work.resolve())
    assert isinstance(manifest["files"], list)
    assert len(manifest["files"]) > 0

    # Every entry has the documented keys.
    required = {"key", "category", "path", "exists", "size_bytes",
                "columns", "indices", "note", "producer"}
    for entry in manifest["files"]:
        missing = required - set(entry)
        assert not missing, (
            f"manifest entry missing keys {missing}: {entry}"
        )
        assert entry["category"] in {"raw", "processed"}, (
            f"unknown category on {entry['key']!r}: "
            f"{entry['category']!r}"
        )
        # Each key is in REGISTRY.
        assert entry["key"] in REGISTRY, (
            f"manifest references unknown REGISTRY key: {entry['key']!r}"
        )

    # At least one raw entry should be present in the bundle (the LP
    # cascade always emits >= 1 v_* parquet).
    raw_present = [e for e in manifest["files"]
                   if e["category"] == "raw" and e["exists"]]
    if must_have_raw:
        assert raw_present, (
            "manifest reports no raw files on disk; the cascade should "
            "have emitted at least one v_*.parquet shard.  "
            f"output_raw exists: {(work / 'output_raw').is_dir()}"
        )

    # Every ``exists=True`` entry points at a real file.
    for entry in manifest["files"]:
        if not entry["exists"]:
            continue
        rel = work / entry["path"]
        assert rel.is_file(), (
            f"manifest claims {entry['key']!r} exists at {rel} but the "
            f"file is missing on disk."
        )

    return manifest


def _assert_no_unexpected_solve_data_csvs(work: Path,
                                          whitelist: frozenset[str]) -> None:
    """Solve_data/ may contain only documented out-of-scope basenames.

    Any other ``.csv`` in ``solve_data/`` is a regression — Phase E's
    writer-port gate failed to cover that producer.  Failure prints the
    unexpected set so the next dispatch knows which writer to lift.
    """
    sd = work / "solve_data"
    if not sd.is_dir():
        return  # cleanest possible state — nothing to validate.
    on_disk = {p.name for p in sd.glob("*.csv")}
    unexpected = on_disk - whitelist
    assert not unexpected, (
        f"Phase H default-mode regression: solve_data/ contains "
        f"unexpected CSVs not in the documented out-of-scope "
        f"whitelist.  Unexpected files: {sorted(unexpected)}.  "
        f"Either gate the producing writer (preferred) or add the "
        f"basename to _DOCUMENTED_OUT_OF_SCOPE_SOLVE_DATA with a "
        f"comment explaining why it's out of scope."
    )


def _assert_no_cross_solve_csvs(work: Path) -> None:
    """The cross-solve carriers ride in ``state.cross_solve_carriers``
    (Phase E-d); the on-disk ``cross_solve/`` directory should not be
    created at all under default mode, or if created, it should not
    contain any ``.csv`` files."""
    cs = work / "cross_solve"
    if not cs.is_dir():
        return
    csvs = sorted(p.name for p in cs.glob("*.csv"))
    assert not csvs, (
        f"Phase H default-mode regression: cross_solve/ contains CSVs "
        f"under the in-memory cascade — Phase E-d migrated the cross-"
        f"solve carriers to in-memory state.cross_solve_carriers.  "
        f"Unexpected files: {csvs}"
    )


def _output_raw_parquets(work: Path) -> list[Path]:
    raw = work / "output_raw"
    if not raw.is_dir():
        return []
    return sorted(raw.glob("v_*.parquet"))


# ---------------------------------------------------------------------------
# Default-mode invariants (in-memory cascade).
# ---------------------------------------------------------------------------


def test_default_mode_work_base_clean_bundle(tmp_path: Path) -> None:
    """Default mode on ``work_base`` produces a clean output bundle:

    * No unexpected CSVs in ``solve_data/`` / ``cross_solve/`` (Phase
      E gate honoured; the documented out-of-scope set is allowed).
    * ``output_raw/v_*.parquet`` exists.
    * ``manifest.json`` schema correct; raw entries map to real files.
    """
    db = _db_or_skip(_FIX_SINGLE_ROLL[0])
    work = tmp_path / "default_mode"
    sols = _run_cascade(db, _FIX_SINGLE_ROLL[1], work, csv_disabled=True)
    assert sols, "default-mode cascade returned no sub-solves"

    # Raw parquet trail must be present.
    parquets = _output_raw_parquets(work)
    assert parquets, (
        f"default mode: no v_*.parquet under {work / 'output_raw'} — "
        f"the cascade's raw-result writer should always emit at least "
        f"one shard."
    )

    # Cascade-internal CSV gate honoured.
    _assert_no_unexpected_solve_data_csvs(
        work, _DOCUMENTED_OUT_OF_SCOPE_SOLVE_DATA,
    )
    _assert_no_cross_solve_csvs(work)

    # Manifest writes successfully and validates.
    _validate_manifest(work, must_have_raw=True)


def test_default_mode_captures_objective(tmp_path: Path) -> None:
    """Capture the default-mode objective on ``work_base``.  This pins
    the value used by the csv-dump-parity test below."""
    db = _db_or_skip(_FIX_SINGLE_ROLL[0])
    work = tmp_path / "default_mode"
    sols = _run_cascade(db, _FIX_SINGLE_ROLL[1], work, csv_disabled=True)
    obj = _final_objective(sols)
    assert math.isfinite(obj), f"objective not finite: {obj}"
    # Sanity: work_base's golden objective is ~4.78e9.  Loose bound.
    assert 1e6 < obj < 1e12, f"work_base objective out of expected band: {obj}"


# ---------------------------------------------------------------------------
# csv-dump mode (CSV emission ON) — both single-roll and multi-roll.
# ---------------------------------------------------------------------------


def test_csv_dump_mode_work_base_emits_legacy_csvs(tmp_path: Path) -> None:
    """With CSV emission ON, ``solve_data/`` should carry the legacy
    CSV set (sample a few key basenames).  Output_raw parquets still
    emit; manifest still writes."""
    db = _db_or_skip(_FIX_SINGLE_ROLL[0])
    work = tmp_path / "csv_dump"
    sols = _run_cascade(db, _FIX_SINGLE_ROLL[1], work, csv_disabled=False)
    assert sols

    sd = work / "solve_data"
    assert sd.is_dir()
    on_disk = {p.name for p in sd.glob("*.csv")}
    # Sample a few high-traffic basenames the gate-on path emits.
    for sample in (
        "p_entity_unitsize.csv",
        "steps_in_use.csv",
        "p_inflation_factor_operations_yearly.csv",
    ):
        assert sample in on_disk, (
            f"csv-dump mode: expected {sample!r} on disk under "
            f"{sd}, but it's missing.  Was the writer-port emission "
            f"gate accidentally left on?  on-disk basenames: "
            f"{sorted(on_disk)[:20]}..."
        )

    # Raw parquets + manifest stay correct.
    assert _output_raw_parquets(work)
    _validate_manifest(work, must_have_raw=True)


def test_objective_parity_default_vs_csv_dump(tmp_path: Path) -> None:
    """The default (gate-on) and csv-dump (gate-off) cascade must
    produce the same final objective — this is the Phase E-e parity
    gate, asserted directly at the cascade-end on ``work_base``."""
    db = _db_or_skip(_FIX_SINGLE_ROLL[0])

    work_default = tmp_path / "default"
    sols_default = _run_cascade(
        db, _FIX_SINGLE_ROLL[1], work_default, csv_disabled=True,
    )
    obj_default = _final_objective(sols_default)

    work_dump = tmp_path / "dump"
    sols_dump = _run_cascade(
        db, _FIX_SINGLE_ROLL[1], work_dump, csv_disabled=False,
    )
    obj_dump = _final_objective(sols_dump)

    assert math.isclose(obj_default, obj_dump, rel_tol=1e-6), (
        f"default-mode objective {obj_default} does not match csv-dump "
        f"mode {obj_dump} within rel_tol=1e-6.  Phase E-e parity gate "
        f"broken."
    )


def test_csv_dump_mode_multi_roll_cascade(tmp_path: Path) -> None:
    """Multi-roll cascade under csv-dump mode (CSV emission ON).
    Asserts: cascade completes with > 1 sub-solve, raw parquets per
    sub-solve are emitted, manifest writes.

    The csv-emission-disabled mode for multi-roll is currently
    blocked by the loader-side ``input.py::_read_p_flow_max`` /
    ``_read_unitsize`` family (not seed-aware).  Verifying the
    csv-dump-mode multi-roll path proves the cascade itself still
    works correctly; the in-memory seed extension to the loader-side
    reads is a follow-up dispatch.
    """
    db = _db_or_skip(_FIX_MULTI_ROLL[0])
    work = tmp_path / "csv_dump_multi"
    sols = _run_cascade(db, _FIX_MULTI_ROLL[1], work, csv_disabled=False)
    assert len(sols) >= 2, (
        f"expected multi-roll fixture to produce >= 2 sub-solves; got "
        f"{len(sols)}: {list(sols)}"
    )
    # Each sub-solve emits its own parquet shards (the cascade's raw
    # writer keys files by ``v_<name>__<solve>.parquet``).  Expect at
    # least one shard per sub-solve for ``v_flow``.
    raw = work / "output_raw"
    flows = sorted(raw.glob("v_flow__*.parquet"))
    assert len(flows) == len(sols), (
        f"expected {len(sols)} v_flow shards (one per sub-solve); got "
        f"{len(flows)}: {[p.name for p in flows]}"
    )
    _validate_manifest(work, must_have_raw=True)


# ---------------------------------------------------------------------------
# Legacy disk-only mode.
# ---------------------------------------------------------------------------


def test_legacy_disk_only_mode_skipped() -> None:
    """Phase E retired the disk-only orchestration path.  The CLI now
    routes through ``run_chain_from_db`` exclusively; ``--csv-dump``
    only toggles emission of cascade-internal CSVs, NOT a different
    orchestration entry point.  This test documents the deprecation."""
    pytest.skip(
        "Legacy disk-only orchestration retired in Phase E (commit "
        "09f3b363).  All cascade dispatches now go through "
        "run_chain_from_db; --csv-dump only flips the writer-port "
        "_write helpers' disk emission gate."
    )


# ---------------------------------------------------------------------------
# External-consumer smoke test (the "fresh eye" gate from the handoff).
# ---------------------------------------------------------------------------


def test_external_consumer_can_load_bundle(tmp_path: Path) -> None:
    """An external consumer opens ``manifest.json``, walks the bundle,
    and computes a tiny summary stat from each present file.  This
    asserts the bundle is self-describing — i.e. a tool can be written
    without knowing FlexTool internals."""
    db = _db_or_skip(_FIX_SINGLE_ROLL[0])
    work = tmp_path / "bundle"
    _run_cascade(db, _FIX_SINGLE_ROLL[1], work, csv_disabled=True)
    _validate_manifest(work, must_have_raw=True)

    manifest_path = work / "manifest.json"
    manifest = json.loads(manifest_path.read_text())

    # Simulate an external tool:
    #   1. Open manifest.json
    #   2. For each present file, load it (parquet via polars, CSV via
    #      polars) and compute a one-stat summary.
    #   3. Assert non-zero stats accumulated (some files are non-empty).
    n_files_inspected = 0
    n_rows_total = 0
    bundle_root = Path(manifest["bundle_root"])
    for entry in manifest["files"]:
        if not entry["exists"]:
            continue
        path = bundle_root / entry["path"]
        assert path.is_file(), (
            f"manifest claims {entry['key']!r} exists but {path} not on "
            f"disk."
        )
        try:
            if path.suffix == ".parquet":
                df = pl.scan_parquet(path).collect()
            elif path.suffix == ".csv":
                df = pl.read_csv(path)
            else:
                # Unknown extension — manifest schema is forward
                # compatible but the smoke test only knows about
                # parquet + CSV.  Skip.
                continue
        except Exception as exc:  # noqa: BLE001
            pytest.fail(
                f"external consumer failed to load {entry['key']!r} at "
                f"{path}: {exc}"
            )
        n_files_inspected += 1
        n_rows_total += df.height

    assert n_files_inspected > 0, (
        "external consumer inspected zero files — manifest claims "
        f"{sum(1 for f in manifest['files'] if f['exists'])} present "
        "files but none could be loaded.  Bundle self-description "
        "broken."
    )
    assert n_rows_total > 0, (
        "external consumer found zero rows across all present files; "
        "the bundle's data shrank to nothing — likely a cascade-side "
        "regression that pruned the raw parquet emit step."
    )


# ---------------------------------------------------------------------------
# Manifest persistence — running the cascade twice (with different work
# folders) does not leak state between bundles.
# ---------------------------------------------------------------------------


def test_two_independent_runs_produce_independent_manifests(
    tmp_path: Path,
) -> None:
    """Two cascade runs into separate work folders produce two
    independent manifests.  Catches any accidental shared mutable
    state in the bundle/registry plumbing."""
    db = _db_or_skip(_FIX_SINGLE_ROLL[0])

    work_a = tmp_path / "run_a"
    work_b = tmp_path / "run_b"
    sols_a = _run_cascade(db, _FIX_SINGLE_ROLL[1], work_a, csv_disabled=True)
    sols_b = _run_cascade(db, _FIX_SINGLE_ROLL[1], work_b, csv_disabled=True)
    assert sols_a and sols_b

    m_a = _validate_manifest(work_a, must_have_raw=True)
    m_b = _validate_manifest(work_b, must_have_raw=True)

    assert m_a["bundle_root"] != m_b["bundle_root"], (
        "two cascade runs produced the same bundle_root in their "
        f"manifests — accidental shared state?  Both report "
        f"{m_a['bundle_root']!r}"
    )

    # Each manifest's files[].path is bundle-root-relative; the same
    # registry keys appear in both manifests (REGISTRY is global), but
    # the resolved absolute paths must differ.
    paths_a = {entry["path"] for entry in m_a["files"] if entry["exists"]}
    paths_b = {entry["path"] for entry in m_b["files"] if entry["exists"]}
    assert paths_a, "manifest a has no present files"
    assert paths_b, "manifest b has no present files"
