"""``dc_power_flow`` scenario — DC OPF on PGLib case14 IEEE.

Mirrors flextool's ``test_dc_power_flow.py::TestPGLibCase14Integration``:
the fixture in ``tests/data/work_dc_power_flow/`` is generated by
``tests/_gen_dc_power_flow.py`` from the MATPOWER ``pglib_opf_case14_ieee.m``
file via ``flextool.process_inputs.read_matpower.create_flextool_db_from_matpower``.

The scenario activates the .mod's ``dc_flow_eq`` family (flextool.mod:3236)
plus the angle-bound preprocessing in
``preprocessing/dc_angle_bounds.py`` (reference angle pinned to 0,
non-reference angles bounded to ±π).  polar_high mirrors this through the
new ``v_angle`` variable + ``dc_flow_eq`` constraint emitted by
:mod:`flextool._dc_power_flow`.

Acceptance: parity at < 1e-6 on the v_obj objective.
"""

import polars as pl

from polar_high import Problem
from flextool.engine_polars import build_flextool, load_flextool
import pytest

pytestmark = pytest.mark.solver


# Phase 3d: case14 fixture exported to ``tests/fixtures/case14_dc_power_flow.json``.
# Scenario name in the DB is ``dc_opf_test``; the legacy workdir was named
# ``work_dc_power_flow`` for human readability.
SCENARIO = "dc_opf_test"


def test_dc_power_flow_parity(scenario_workdir):
    work = scenario_workdir(SCENARIO, db_fixture="case14")
    data = load_flextool(work)

    # Fixture sanity — DC PF data populated.
    assert data.node_dc_power_flow is not None
    assert data.node_dc_power_flow.height == 14   # 14 buses
    assert data.connection_dc_power_flow is not None
    assert data.connection_dc_power_flow.height == 20   # 20 lines
    assert data.node_reference_angle is not None
    assert data.node_reference_angle.height == 1  # bus_1 is the slack
    assert data.p_connection_susceptance is not None

    pb = Problem()
    build_flextool(pb, data)

    # Constraint families are wired.
    cstr_names = pb.cstr_names()
    assert "v_angle" in [v.name for v in pb._vars.values()]
    assert "dc_flow_eq" in cstr_names
    assert "dc_reference_angle_eq" in cstr_names

    sol = pb.solve()
    assert sol.optimal

    flextool_obj = pl.read_parquet(
        work / "output_raw" / "v_obj__dispatch.parquet"
    )["objective"][0]
    assert abs(sol.obj - flextool_obj) / max(1.0, flextool_obj) < 1e-6
