"""
Direct HiGHS solution → parquet extractor.

Replaces the current pipeline
    HiGHS → flextool.sol → glpsol (phase 3) → output_raw/*.csv → read_variables.py
with
    HiGHS (in-memory) → parquet → downstream pandas.

Design
------
HiGHS exposes the MPS column names (as generated by glpsol's --wfreemps)
through ``highspy.Highs.allVariableNames()`` and the solution through
``Highs.getSolution().col_value``.  The two arrays are index-aligned.

MPS variable names look like::

    <var_name>[<idx1>,<idx2>,...,<period>,<time>]   # time-indexed vars
    <var_name>[<idx1>,...,<period>]                 # period-only vars (e.g. v_invest)

Splitting on '[', ',' and ']' recovers the indices.  This assumes entity
names never contain commas or brackets — already a GLPSOL requirement for
unambiguous MPS emission.

Output CSVs from the current glpsol pathway contain only the
``dt_realize_dispatch`` timesteps — rolling-window solves compute a longer
horizon but only realize the first chunk.  We replicate that filter inside
the single pass over HiGHS names (O(1) set lookup) so non-realized rows
are never materialised.

Storage layout: wide.  Row MultiIndex = ``(solve, period, time)`` (or
``(solve, period)`` for non-time vars), column (Multi)Index = the
remaining variable indices.  Matches the shape of
``read_variables.read_variables`` outputs exactly, so downstream
``calc_*.py`` code is unchanged.  Persisted via
``flextool.lean_parquet.write_lean_parquet`` — compact level-name
metadata in the parquet footer.

Public API
----------
* :data:`VARIABLE_SPECS` — list of :class:`VariableSpec` describing every
  variable that has parquet coverage.  Add a new line here to add a new
  variable.
* :func:`extract_variable` — single variable → wide DataFrame.
* :func:`write_variable_parquet` — single variable → parquet file.
* :func:`write_all_variables` — iterate :data:`VARIABLE_SPECS` and write
  one parquet per variable for a given solve.
* Loading: use :func:`flextool.lean_parquet.read_lean_parquet` directly.

Usage from solver_runner (after a successful ``h.run()``)::

    from flextool.process_outputs.read_highs_solution import write_all_variables
    write_all_variables(
        h, solve_name=current_solve,
        output_dir=wf / "output_raw",
        realized_dispatch_csv=wf / "solve_data/realized_dispatch.csv",
    )
"""
from __future__ import annotations

import argparse
import logging
import re
from pathlib import Path
from typing import NamedTuple, Sequence, TYPE_CHECKING

import pandas as pd

from flextool.lean_parquet import write_lean_parquet

if TYPE_CHECKING:
    import highspy

_logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Variable registry
# ---------------------------------------------------------------------------


class VariableSpec(NamedTuple):
    """Describes one HiGHS result quantity for parquet extraction.

    Covers three source arrays on the solved ``Highs`` instance:

    * ``col_value`` (default) — primal variable values, keyed by
      ``allVariableNames()``.
    * ``col_dual`` — variable reduced costs, same keying as
      ``col_value``.  Used for ``v_invest.dual`` / ``v_divest.dual``.
    * ``row_dual`` — constraint dual values, keyed by
      ``getLp().row_names_``.  Used for investment-cap duals,
      ``nodeBalance_eq``, CO2-limit duals, …

    Attributes
    ----------
    name:
        Name as it appears in the MPS.  Variable name for
        ``col_value``/``col_dual`` sources; constraint name for
        ``row_dual``.  Must match the prefix in ``<name>[idx1,...]``.
    col_names:
        Names of the leading "column" indices before the trailing
        ``period[, time]`` (or just ``period``, or nothing — see
        :attr:`has_time` and :attr:`has_period`).
    has_time:
        True when indexed by both period and time.  False for
        period-only quantities.
    has_period:
        True (default) when the trailing index (after ``col_names``)
        includes at least a period.  False for quantities indexed only
        by the column fields (e.g. ``co2_max_total[g]``) — in that case
        the row index collapses to just ``(solve,)``.
    source:
        Which HiGHS array the values come from — one of
        ``"col_value"`` (default), ``"col_dual"``, ``"row_dual"``.
    value_scale:
        Multiplier applied to every raw value.  Typically ``1e6``
        (``1 / scale_the_objective``) for duals.
    output_name:
        Parquet file prefix.  Defaults to :attr:`name`.  Set when the
        constraint name differs from the desired output identifier —
        e.g. constraint ``maxInvest_entity_period`` is written as
        ``v_dual_maxInvest_period``.
    """

    name: str
    col_names: tuple[str, ...]
    has_time: bool = True
    has_period: bool = True
    source: str = "col_value"
    value_scale: float = 1.0
    output_name: str | None = None
    # Some constraint names have extra "bookkeeping" indices we don't
    # want in the output — typically a leading ``c`` (= solve_current,
    # already captured by ``solve_name``) and trailing "previous-step"
    # indices.  ``leading_ignore`` / ``trailing_ignore`` drop that many
    # positions at the start / end of the bracket list, so
    # ``col_names`` lines up with the positions that actually matter.
    # Example — ``nodeBalance_eq[c,n,d,t,tp,tpwt,dp,tpws]`` → use
    # ``col_names=("node",), has_time=True, leading_ignore=1,
    # trailing_ignore=4``.
    leading_ignore: int = 0
    trailing_ignore: int = 0


# Registry — add a new line here to add a new variable to the pipeline.
#
# ``scale_the_objective`` (flextool_base.dat) is 1e-6, so every dual needs
# multiplication by 1e6 to undo the objective scaling — matches what the
# GLPSOL CSV writer does via ``/ scale_the_objective``.
_INV_SCALE_THE_OBJECTIVE = 1e6

# Helper — every investment-constraint-dual entry uses the same scale to
# undo ``scale_the_objective`` and writes its parquet under ``v_dual_<…>``.
def _invest_dual(mps_name: str, col: str, output_suffix: str) -> VariableSpec:
    return VariableSpec(
        name=mps_name,
        col_names=(col,),
        has_time=False,
        source="row_dual",
        value_scale=_INV_SCALE_THE_OBJECTIVE,
        output_name=f"v_dual_{output_suffix}",
    )


VARIABLE_SPECS: list[VariableSpec] = [
    # -- Time-indexed decision variables ------------------------------------
    VariableSpec("v_flow",             ("process", "source", "sink")),
    VariableSpec("v_ramp",             ("process", "source", "sink")),
    VariableSpec("v_reserve",          ("process", "reserve", "upDown", "node")),
    VariableSpec("v_state",            ("node",)),
    VariableSpec("v_online_linear",    ("process",)),
    VariableSpec("v_startup_linear",   ("process",)),
    VariableSpec("v_shutdown_linear",  ("process",)),
    VariableSpec("v_online_integer",   ("process",)),
    VariableSpec("v_startup_integer",  ("process",)),
    VariableSpec("v_shutdown_integer", ("process",)),
    VariableSpec("v_angle",            ("node",)),

    # -- Time-indexed slack / penalty variables -----------------------------
    VariableSpec("vq_state_up",        ("node",)),
    VariableSpec("vq_state_down",      ("node",)),
    VariableSpec("vq_reserve",         ("reserve", "upDown", "group")),
    VariableSpec("vq_inertia",         ("group",)),
    VariableSpec("vq_non_synchronous", ("group",)),
    VariableSpec("vq_state_up_group",  ("group",)),

    # -- Period-only (no time) decision / slack variables -------------------
    VariableSpec("v_invest",           ("entity",), has_time=False),
    VariableSpec("v_divest",           ("entity",), has_time=False),
    VariableSpec("vq_capacity_margin", ("group",),  has_time=False),

    # -- Investment-cap duals (period-only, simple 1/scale transform) -------
    _invest_dual("maxInvest_entity_period",          "entity", "maxInvest_period"),
    _invest_dual("maxInvest_entity_total",           "entity", "maxInvest_total"),
    _invest_dual("maxCumulative_capacity",           "entity", "maxCumulative"),
    _invest_dual("maxInvestGroup_entity_period",     "group",  "maxInvestGroup_period"),
    _invest_dual("maxInvestGroup_entity_total",      "group",  "maxInvestGroup_total"),
    _invest_dual("maxInvestGroup_entity_cumulative", "group",  "maxInvestGroup_cumulative"),

    # -- CO2 emission-cap duals ---------------------------------------------
    # The model writes ``co2_max_*.dual / scale_the_objective``.  Downstream
    # Python processing applies the extra ``/1000`` (scaled RHS) and
    # ``/inflation`` corrections — not our concern here.
    VariableSpec(
        name="co2_max_period", col_names=("group",),
        has_time=False, source="row_dual",
        value_scale=_INV_SCALE_THE_OBJECTIVE,
        output_name="v_dual_co2_max_period",
    ),
    VariableSpec(
        name="co2_max_total", col_names=("group",),
        has_time=False, has_period=False, source="row_dual",
        value_scale=_INV_SCALE_THE_OBJECTIVE,
        output_name="v_dual_co2_max_total",
    ),

    # NOT COVERED YET (still produced by glpsol phase 3):
    # * v_dual_node_balance — per-period inflation scaling needs a
    #   custom writer (see write_v_dual_node_balance below).
    # * v_dual_reserve__upDown__group__period__t — max() across up to 3
    #   constraint duals per (r,ud,g,d,t); deferred.
    # * v_dual_invest_{unit,connection,node} — v_invest.dual split by
    #   entity class (see write_v_dual_invest_by_class below).
    # * v_obj — scalar, see write_v_obj below.
]


# ---------------------------------------------------------------------------
# Core helpers
# ---------------------------------------------------------------------------


def _load_realized_set(
    realized_dispatch_csv: Path | str | None,
) -> set[tuple[str, str]] | None:
    """Return {(period, time), …} from ``realized_dispatch.csv``, or None."""
    if realized_dispatch_csv is None:
        return None
    path = Path(realized_dispatch_csv)
    if not path.exists():
        _logger.warning("realized_dispatch file missing, writing all timesteps: %s", path)
        return None
    realized = pd.read_csv(path)
    period_col = "period"
    time_col = "step" if "step" in realized.columns else "time"
    return set(
        zip(
            realized[period_col].astype(str).to_list(),
            realized[time_col].astype(str).to_list(),
        )
    )


def _load_realized_periods(
    realized_periods_csv: Path | str | None,
) -> set[str] | None:
    """Return {period, …} from a ``period``-only CSV, or None."""
    if realized_periods_csv is None:
        return None
    path = Path(realized_periods_csv)
    if not path.exists():
        _logger.warning("realized periods file missing, writing all periods: %s", path)
        return None
    realized = pd.read_csv(path)
    return set(realized["period"].astype(str).to_list())


def _name_regex(var_name: str) -> re.Pattern[str]:
    """Return a compiled regex matching ``<var_name>[...]``."""
    return re.compile(rf"^{re.escape(var_name)}\[(.+)\]$")


def extract_variable(
    h: "highspy.Highs",
    name: str,
    col_names: Sequence[str],
    *,
    solve_name: str,
    has_time: bool = True,
    has_period: bool = True,
    source: str = "col_value",
    value_scale: float = 1.0,
    realized_dispatch_csv: Path | str | None = None,
    realized_periods_csv: Path | str | None = None,
    leading_ignore: int = 0,
    trailing_ignore: int = 0,
) -> pd.DataFrame:
    """Extract one quantity from a solved HiGHS instance as a wide DataFrame.

    Parameters mirror :class:`VariableSpec` plus ``solve_name`` (tag
    inserted into the row MultiIndex — typically the current solve name).
    ``source`` selects which aligned array HiGHS exposes —
    ``"col_value"``, ``"col_dual"`` (both keyed by
    ``allVariableNames()``) or ``"row_dual"`` (keyed by
    ``getLp().row_names_``).  ``value_scale`` is applied once per raw
    value (typically ``1e6`` for dual sources, to undo
    ``scale_the_objective``).

    ``realized_dispatch_csv`` filters (period, time) pairs for time-
    indexed quantities; ``realized_periods_csv`` filters periods for
    period-only quantities.  ``has_period=False`` means the quantity
    has no period index at all — row index collapses to just
    ``(solve,)`` (used for ``co2_max_total[g]``).

    Returns
    -------
    DataFrame
        Wide layout — row index ``(solve,)`` / ``(solve, period)`` /
        ``(solve, period, time)`` depending on the has_* flags.  Column
        MultiIndex when ``len(col_names) >= 2``, a single-level ``Index``
        otherwise.  Missing combinations are filled with 0.0 to match
        the glpsol CSV output.
    """
    if source == "row_dual":
        # Constraint names are stored on the LP struct, not exposed via
        # a bulk getter on Highs itself — ``getLp().row_names_`` is the
        # fast path (no per-row Python call).
        names = h.getLp().row_names_
        values = h.getSolution().row_dual
    elif source == "col_dual":
        names = h.allVariableNames()
        values = h.getSolution().col_dual
    elif source == "col_value":
        names = h.allVariableNames()
        values = h.getSolution().col_value
    else:
        raise ValueError(
            f"Unknown source '{source}' — expected one of "
            "'col_value', 'col_dual', 'row_dual'"
        )
    if len(names) != len(values):
        raise RuntimeError(
            f"HiGHS name / value length mismatch for '{name}' "
            f"(source={source}): {len(names)} names vs {len(values)} values"
        )

    prefix = f"{name}["
    pattern = _name_regex(name)
    trailing = (2 if has_time else 1) if has_period else 0
    expected_arity = (
        leading_ignore + len(col_names) + trailing + trailing_ignore
    )
    realized_dt = _load_realized_set(realized_dispatch_csv) if has_time else None
    realized_p = (
        _load_realized_periods(realized_periods_csv)
        if (has_period and not has_time) else None
    )

    if not has_period:
        row_index_names = ["solve"]
    elif has_time:
        row_index_names = ["solve", "period", "time"]
    else:
        row_index_names = ["solve", "period"]

    # Flat accumulators → one DataFrame + one pivot at the end.  Cheaper
    # than building nested dicts for the typical tens-of-thousands-of-vars
    # solve.
    row_keys: list[tuple[str, ...]] = []
    col_keys: list[tuple[str, ...]] = []
    vals: list[float] = []

    for item_name, val in zip(names, values):
        if not item_name.startswith(prefix):
            continue
        m = pattern.match(item_name)
        if not m:
            _logger.warning("Unrecognised %s name: %s", name, item_name)
            continue
        parts = m.group(1).split(",")
        if len(parts) != expected_arity:
            _logger.warning(
                "Unexpected %s arity (%d, expected %d): %s",
                name, len(parts), expected_arity, item_name,
            )
            continue
        # Slice positions: [leading_ignore : leading_ignore+ncol] → cols;
        # [ncol+leading : ncol+leading+trailing] → period/time;
        # [-trailing_ignore:] → dropped (must not affect indexing when 0).
        col_start = leading_ignore
        col_end = col_start + len(col_names)
        col_vals = tuple(parts[col_start:col_end])
        if has_period and has_time:
            period, time = parts[col_end], parts[col_end + 1]
            if realized_dt is not None and (period, time) not in realized_dt:
                continue
            row_keys.append((solve_name, period, time))
        elif has_period:
            period = parts[col_end]
            if realized_p is not None and period not in realized_p:
                continue
            row_keys.append((solve_name, period))
        else:
            row_keys.append((solve_name,))
        col_keys.append(col_vals)
        vals.append(float(val) * value_scale)

    # No variable values matched.  Phase-3 CSV writers would still iterate
    # ``for {s in solve_current, (d, t) in dt_realize_dispatch}`` — i.e.
    # produce N_rows × 0-columns rather than (0, 0).  Downstream pandas
    # code (``DataFrame.mul(axis=1, level=0)``) breaks when one operand
    # has an empty MultiIndex row while the other has populated rows, so
    # fabricate the same ``(solve, period[, time])`` row index here using
    # the realized-dispatch data the caller already pointed us at.
    if not vals:
        if len(col_names) >= 2:
            empty_cols: pd.Index = pd.MultiIndex.from_tuples([], names=list(col_names))
        else:
            empty_cols = pd.Index([], name=col_names[0])

        row_keys_synth: list[tuple] = []
        if has_period and has_time and realized_dt is not None:
            row_keys_synth = [(solve_name, d, t) for (d, t) in realized_dt]
        elif has_period and not has_time and realized_p is not None:
            row_keys_synth = [(solve_name, d) for d in realized_p]
        elif not has_period:
            row_keys_synth = [(solve_name,)]

        if not row_keys_synth:
            if len(row_index_names) == 1:
                empty_rows: pd.Index = pd.Index([], name=row_index_names[0])
            else:
                empty_rows = pd.MultiIndex.from_tuples([], names=row_index_names)
            return pd.DataFrame(index=empty_rows, columns=empty_cols, dtype=float)

        if len(row_index_names) == 1:
            rows = pd.Index(
                [k[0] for k in row_keys_synth], name=row_index_names[0],
            )
        else:
            rows = pd.MultiIndex.from_tuples(
                row_keys_synth, names=row_index_names,
            )
        return pd.DataFrame(index=rows, columns=empty_cols, dtype=float)

    long_data: dict[str, list] = {
        rn: [k[i] for k in row_keys] for i, rn in enumerate(row_index_names)
    }
    for i, cn in enumerate(col_names):
        long_data[cn] = [k[i] for k in col_keys]
    long_data["value"] = vals

    long = pd.DataFrame(long_data)
    wide = long.pivot_table(
        index=row_index_names,
        columns=list(col_names),
        values="value",
        fill_value=0.0,
    )
    return wide


def write_variable_parquet(
    h: "highspy.Highs",
    spec: VariableSpec,
    *,
    solve_name: str,
    output_dir: Path | str,
    realized_dispatch_csv: Path | str | None = None,
    realized_periods_csv: Path | str | None = None,
    file_name: str | None = None,
) -> Path:
    """Extract the quantity described by *spec* and write a per-solve parquet.

    File name defaults to ``{spec.output_name or spec.name}__{solve}.parquet``
    so parallel / rolling / nested solves don't collide.  Merging
    per-solve files into a single ``{output_name}.parquet`` is a cheap
    post-processing step (one ``pd.concat``).
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    df = extract_variable(
        h, spec.name, spec.col_names,
        solve_name=solve_name,
        has_time=spec.has_time,
        has_period=spec.has_period,
        source=spec.source,
        value_scale=spec.value_scale,
        realized_dispatch_csv=realized_dispatch_csv,
        realized_periods_csv=realized_periods_csv,
        leading_ignore=spec.leading_ignore,
        trailing_ignore=spec.trailing_ignore,
    )
    if file_name is None:
        file_name = f"{spec.output_name or spec.name}__{solve_name}.parquet"
    path = output_dir / file_name
    write_lean_parquet(df, path)
    _logger.info(
        "Wrote %s for solve '%s' → %s (shape %s)",
        spec.output_name or spec.name, solve_name, path, df.shape,
    )
    return path


# ---------------------------------------------------------------------------
# Custom writers for outputs that don't fit the plain VariableSpec pattern
# (scalar, entity-class split, per-period transform).
# ---------------------------------------------------------------------------


def _load_entity_class(work_folder: Path, set_name: str) -> set[str]:
    """Load the members of an entity class directly from ``input/``.

    Sourcing from ``input/`` keeps the Category C custom writers
    independent of phase 3 (which runs AFTER our writers inside
    ``_run_highs``) — important for the planned phase-3 retirement.

    ``set_name`` maps to files like ``input/process_unit.csv``,
    ``input/process_connection.csv``, ``input/node.csv``.  The input
    files are long-format with a single column named after the set.
    """
    path = work_folder / "input" / f"{set_name}.csv"
    if not path.exists():
        return set()
    df = pd.read_csv(path)
    if df.empty or len(df.columns) == 0:
        return set()
    return set(df.iloc[:, 0].astype(str).tolist())


def _load_inflation_factor(work_folder: Path) -> dict[str, float]:
    """``{period: p_inflation_factor_operations_yearly}``.

    Written by the model during phase 1 (derived parameter moved above
    ``solve;``).
    """
    path = work_folder / "solve_data" / "p_inflation_factor_operations_yearly.csv"
    if not path.exists():
        return {}
    df = pd.read_csv(path)
    period_col = "period"
    value_col = [c for c in df.columns if c not in ("solve", "period")][0]
    return dict(zip(df[period_col].astype(str), df[value_col].astype(float)))


def _load_complete_period_share_of_year(work_folder: Path) -> dict[str, float]:
    """``{period: complete_period_share_of_year}`` (phase-1 dump)."""
    path = work_folder / "solve_data" / "complete_period_share_of_year.csv"
    if not path.exists():
        return {}
    df = pd.read_csv(path)
    period_col = "period"
    value_col = [c for c in df.columns if c not in ("solve", "period")][0]
    return dict(zip(df[period_col].astype(str), df[value_col].astype(float)))


def write_v_obj(
    h: "highspy.Highs",
    *,
    solve_name: str,
    output_dir: Path | str,
) -> Path:
    """Write ``v_obj__{solve}.parquet`` — objective value for this solve.

    Model writes ``total_cost.val / scale_the_objective``.  HiGHS's
    ``getObjectiveValue()`` returns the raw (scaled) value; we undo the
    scaling.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    obj = float(h.getObjectiveValue()) * _INV_SCALE_THE_OBJECTIVE
    df = pd.DataFrame(
        {"objective": [obj]},
        index=pd.Index([solve_name], name="solve"),
    )
    path = output_dir / f"v_obj__{solve_name}.parquet"
    write_lean_parquet(df, path)
    _logger.info("Wrote v_obj for solve '%s' → %s (%.10g)", solve_name, path, obj)
    return path


def write_v_dual_invest_by_class(
    h: "highspy.Highs",
    *,
    solve_name: str,
    output_dir: Path | str,
    realized_periods_csv: Path | str | None = None,
    work_folder: Path | str | None = None,
) -> list[Path]:
    """Write v_invest reduced costs split by entity class.

    Produces three parquet files — ``v_dual_invest_unit__{solve}``,
    ``v_dual_invest_connection__{solve}``, ``v_dual_invest_node__{solve}``
    — each containing the ``v_invest.dual`` values for entities in the
    corresponding class (``process_unit``, ``process_connection``,
    ``node``).  Matches the three separate CSVs phase 3 writes.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    wf = Path(work_folder) if work_folder is not None else output_dir.parent

    duals = extract_variable(
        h, "v_invest", ("entity",),
        solve_name=solve_name, has_time=False, source="col_dual",
        realized_periods_csv=realized_periods_csv,
    )

    classes = {
        "process_unit": _load_entity_class(wf, "process_unit"),
        "process_connection": _load_entity_class(wf, "process_connection"),
        "node": _load_entity_class(wf, "node"),
    }
    output_suffixes = {
        "process_unit": "unit",
        "process_connection": "connection",
        "node": "node",
    }

    paths: list[Path] = []
    for cls_name, members in classes.items():
        keep = [c for c in duals.columns if c in members]
        subset = duals[keep].copy() if keep else duals.iloc[:, :0]
        # Preserve the single-level column index name for round-trip
        subset.columns.name = "entity"
        fname = f"v_dual_invest_{output_suffixes[cls_name]}__{solve_name}.parquet"
        path = output_dir / fname
        write_lean_parquet(subset, path)
        _logger.info(
            "Wrote v_dual_invest_%s for solve '%s' → %s (shape %s)",
            output_suffixes[cls_name], solve_name, path, subset.shape,
        )
        paths.append(path)
    return paths


def write_v_dual_node_balance(
    h: "highspy.Highs",
    *,
    solve_name: str,
    output_dir: Path | str,
    realized_dispatch_csv: Path | str | None = None,
    work_folder: Path | str | None = None,
) -> Path:
    """Write ``v_dual_node_balance__{solve}.parquet``.

    Model formula (for n not in nodeStateBlock)::

        -nodeBalance_eq[c, n, d, t, tp, tpwt, dp, tpws].dual
         / p_inflation_factor_operations_yearly[d]
         / scale_the_objective

    Equivalently, raw-dual × (−1e6 / inflation[d]).  Nodes in
    ``nodeStateBlock`` use ``nodeBalanceBlock_eq`` summed over
    period_block_time — NOT YET IMPLEMENTED HERE.  Scenarios using
    representative periods with block storage will see missing/zero
    entries for those nodes.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    wf = Path(work_folder) if work_folder is not None else output_dir.parent

    # Raw duals × −1e6; per-period inflation division applied after.
    df = extract_variable(
        h, "nodeBalance_eq", ("node",),
        solve_name=solve_name, has_time=True, source="row_dual",
        value_scale=-_INV_SCALE_THE_OBJECTIVE,
        realized_dispatch_csv=realized_dispatch_csv,
        leading_ignore=1,   # ``c`` (solve) — already captured in row index
        trailing_ignore=4,  # tp, tpwt, dp, tpws — bookkeeping only
    )

    if not df.empty:
        inflation = _load_inflation_factor(wf)
        if inflation:
            # Divide each row by its period's inflation factor.  Rows
            # whose period isn't in the dict keep a unity divisor.
            periods = df.index.get_level_values("period")
            divisors = pd.Series(
                [inflation.get(str(p), 1.0) for p in periods],
                index=df.index,
                dtype=float,
            )
            df = df.div(divisors, axis=0)

    path = output_dir / f"v_dual_node_balance__{solve_name}.parquet"
    write_lean_parquet(df, path)
    _logger.info(
        "Wrote v_dual_node_balance for solve '%s' → %s (shape %s)",
        solve_name, path, df.shape,
    )
    return path


def write_v_dual_reserve_balance(
    h: "highspy.Highs",
    *,
    solve_name: str,
    output_dir: Path | str,
    realized_dispatch_csv: Path | str | None = None,
    work_folder: Path | str | None = None,
) -> Path:
    """Write ``v_dual_reserve__upDown__group__period__t__{solve}.parquet``.

    Model formula takes ``max()`` over up to three constraint duals per
    ``(r, ud, g, r_m, d, t)``:

        * ``reserveBalance_timeseries_eq`` (most common method)
        * ``reserveBalance_dynamic_eq``
        * ``reserveBalance_up_n_1_eq`` / ``reserveBalance_down_n_1_eq``
          (N-1 security)

    applied after period scaling
    ``× complete_period_share_of_year[d] / p_inflation_factor_operations_yearly[d]``.

    SIMPLIFIED HERE: currently extracts only the timeseries-equation
    duals.  For ``(r, ud, g)`` that use the ``timeseries_only`` method
    (the common case covered by all the test scenarios) this is exact.
    Groups using ``dynamic`` or ``n_1`` methods will be under-reported
    until the full ``max()`` logic is ported.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    wf = Path(work_folder) if work_folder is not None else output_dir.parent
    out_path = output_dir / (
        f"v_dual_reserve__upDown__group__period__t__{solve_name}.parquet"
    )

    # reserveBalance_timeseries_eq indices: r, ud, g, r_m, d, t (6).
    # Include ``r_m`` (method) in col_names then drop it after extraction.
    df = extract_variable(
        h, "reserveBalance_timeseries_eq",
        ("reserve", "upDown", "group", "method"),
        solve_name=solve_name, has_time=True, source="row_dual",
        realized_dispatch_csv=realized_dispatch_csv,
    )

    if df.empty:
        write_lean_parquet(df.droplevel("method", axis=1) if "method" in (df.columns.names or []) else df, out_path)
        _logger.info(
            "Wrote v_dual_reserve_balance for solve '%s' → %s (empty)",
            solve_name, out_path,
        )
        return out_path

    # Drop ``method`` level — phase 3 CSV has only (reserve, upDown, group).
    # Each (r, ud, g) typically has at most one active method in the
    # MPS, so the sum equals the single non-zero dual.
    df = (
        df.T.groupby(level=["reserve", "upDown", "group"]).sum().T
    )

    # Apply × period_share / inflation per period.
    inflation = _load_inflation_factor(wf)
    period_share = _load_complete_period_share_of_year(wf)
    periods = df.index.get_level_values("period")
    factor = pd.Series(
        [
            period_share.get(str(p), 1.0) / inflation.get(str(p), 1.0)
            for p in periods
        ],
        index=df.index, dtype=float,
    )
    df = df.mul(factor, axis=0)

    write_lean_parquet(df, out_path)
    _logger.info(
        "Wrote v_dual_reserve_balance for solve '%s' → %s (shape %s)",
        solve_name, out_path, df.shape,
    )
    return out_path


def _is_first_solve_from_p_model(work_folder: Path) -> bool:
    """True iff ``input/p_model.csv`` says ``solveFirst`` is 1 (or missing)."""
    path = work_folder / "input" / "p_model.csv"
    if not path.exists():
        return True
    df = pd.read_csv(path)
    matches = df.loc[df["modelParam"] == "solveFirst", "p_model"]
    if matches.empty:
        return True
    return bool(int(matches.iloc[0]))


def _actual_solve_name(work_folder: Path, fallback: str) -> str:
    """Return the roll-level solve name from ``solve_data/solve_current.csv``.

    In rolling-window scenarios, ``solver.run(complete_solve[solve])`` is
    invoked with the PARENT solve name (the ``complete_solve``) while
    every phase-1 CSV in ``solve_data/`` stores the child ROLL name
    under its ``solve`` column (the set ``solve_current`` in the model).
    When filtering those CSVs or emitting CSV rows whose format the model
    produced, use the ROLL name — otherwise Python output won't line up
    with phase 3's.
    """
    path = work_folder / "solve_data" / "solve_current.csv"
    if not path.exists():
        return fallback
    df = pd.read_csv(path)
    if df.empty or len(df.columns) == 0:
        return fallback
    return str(df.iloc[0, 0])




def write_all_variables(
    h: "highspy.Highs",
    *,
    solve_name: str,
    output_dir: Path | str,
    realized_dispatch_csv: Path | str | None = None,
    realized_periods_csv: Path | str | None = None,
    specs: Sequence[VariableSpec] | None = None,
) -> list[Path]:
    """Iterate :data:`VARIABLE_SPECS` (or a custom list) and write parquets.

    Returns the list of paths written, one per variable.  Each variable
    is independent — failure on one is logged and does not abort the
    remaining ones, so one bad variable can't lose the whole run.
    """
    specs = specs if specs is not None else VARIABLE_SPECS
    written: list[Path] = []
    for spec in specs:
        try:
            path = write_variable_parquet(
                h, spec,
                solve_name=solve_name,
                output_dir=output_dir,
                realized_dispatch_csv=realized_dispatch_csv,
                realized_periods_csv=realized_periods_csv,
            )
            written.append(path)
        except Exception as exc:
            _logger.warning(
                "parquet extraction failed for %s (solve '%s'): %s",
                spec.output_name or spec.name, solve_name, exc,
            )

    # Custom writers for outputs that don't fit a plain VariableSpec.
    _custom_writers = (
        ("v_obj", lambda: write_v_obj(
            h, solve_name=solve_name, output_dir=output_dir,
        )),
        ("v_dual_invest_{unit,connection,node}", lambda: write_v_dual_invest_by_class(
            h, solve_name=solve_name, output_dir=output_dir,
            realized_periods_csv=realized_periods_csv,
        )),
        ("v_dual_node_balance", lambda: write_v_dual_node_balance(
            h, solve_name=solve_name, output_dir=output_dir,
            realized_dispatch_csv=realized_dispatch_csv,
        )),
        ("v_dual_reserve_balance", lambda: write_v_dual_reserve_balance(
            h, solve_name=solve_name, output_dir=output_dir,
            realized_dispatch_csv=realized_dispatch_csv,
        )),
        # ``entity_all_capacity`` moved to ``handoff_writers.py`` — it's
        # conceptually a solve-to-solve handoff (accumulates across
        # solves) and needs the same CSV layout phase 3 produces, not a
        # per-solve parquet.
    )
    for label, fn in _custom_writers:
        try:
            result = fn()
            if isinstance(result, list):
                written.extend(result)
            else:
                written.append(result)
        except Exception as exc:
            _logger.warning(
                "custom writer failed for %s (solve '%s'): %s",
                label, solve_name, exc,
            )
    return written


# ---------------------------------------------------------------------------
# Standalone / offline test entry point
# ---------------------------------------------------------------------------


def _standalone_from_files(
    mps_file: Path, sol_file: Path, solve_name: str, out_dir: Path
) -> list[Path]:
    """Re-read a HiGHS model + solution offline and write all registered vars."""
    import highspy  # local import — the runtime path imports lazily

    h = highspy.Highs()
    status = h.readModel(str(mps_file))
    if status != highspy.HighsStatus.kOk:
        raise RuntimeError(f"HiGHS failed to read MPS: {mps_file}")
    status = h.readSolution(str(sol_file), 0)
    if status != highspy.HighsStatus.kOk:
        raise RuntimeError(
            f"HiGHS failed to read solution file: {sol_file} "
            f"(status={status}).  Try re-solving instead."
        )
    return write_all_variables(h, solve_name=solve_name, output_dir=out_dir)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    parser.add_argument("--mps", type=Path, required=True, help="MPS file")
    parser.add_argument(
        "--sol", type=Path, required=True,
        help="HiGHS solution file (write_solution_style=0; "
             "glpsol-style may not be re-readable)",
    )
    parser.add_argument("--solve", required=True, help="Solve name tag")
    parser.add_argument("--out", type=Path, required=True, help="Output dir")
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO)
    paths = _standalone_from_files(args.mps, args.sol, args.solve, args.out)
    for p in paths:
        print(f"Wrote {p}")


if __name__ == "__main__":
    main()
